### ISSUE TITLE
Issue when running npm run sandbox:start

### ISSUE THREAD

**Issue by kalouo** [stove-labs/tezos-starter-kit#11]
With `npm run sandbox:start` I keep getting the following:

Any ideas? 

I am on on Node v12.16.1. 

Thanks in advance.

```
Omars-MacBook-Pro:tezos-starter-kit omar$ npm run sandbox:start

> tezos-starter-kit@1.0.0 sandbox:start /Users/omar/Desktop/Repositories/tezos-starter-kit
> ./scripts/sandbox/start_ganache-cli.sh

Ganache CLI v6.10.0-tezos.1 (ganache-core: 2.11.0-tezos.2)

Available Accounts
==================
alice 100 TEZ
  pk: edpkvGfYw3LyB1UcCahKQk4rF2tvbMUk8GFiTuMjL75uGXrpvKXhjn
  pkh: tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
bob 100 TEZ
  pk: edpkurPsQ8eUApnLUJ9ZPDvu98E8VNj4KtJa1aZr16Cr5ow5VHKnz4
  pkh: tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6
eve 100 TEZ
  pk: edpku9qEgcyfNNDK6EpMvu5SqXDqWRLuxdMxdyH12ivTUuB1KXfGP4
  pkh: tz1MnmtP4uAcgMpeZN6JtyziXeFqqwQG6yn6
mallory 100 TEZ
  pk: edpkujwsG5JMrWVXQwmRMBoR9yJkokRbn6wy3monpQKBpnZTs1ogRR
  pkh: tz1R2oNqANNy2vZhnZBJc8iMEqW79t85Fv7L

Private Keys
==================
edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq (alice)
edsk3RFfvaFaxbHx8BMtEW1rKQcPtDML3LXjNqMNLCzC3wLC1bWbAt (bob)
edsk3Sb16jcx9KrgMDsbZDmKnuN11v4AbTtPBgBSBTqYftd8Cq3i1e (eve)
edsk3W5Fz1yWK39sLY6vidmgkfmGAXh6V2JqUiri9W1pFeeYWbFbJL (mallory)

Flextesa:  Clearing root: `/tmp/mini-delphi` 

Flextesa:
  Genesis-block-hash not set, using:
  `BMb5281RUmv4tf7ueSRwgrrnWSCZmEq9fCWABNuhw6X2ejKauJ6` (corresponding
  chain-id: `NetXdrsXvmefSf6`) (from user choice: “Random”).

Flextesa:  Starting up the network. 

Flextesa: 
  Activating protocol PsDELPH1Kxsxt8f9eWbxQeRxkjfbxoqM52jvs5Y5fBxWWh4ifpo


Flextesa:  Checking for all levels to be ≥ 1 (nodes: N000) 

Flextesa:  Network started, preparing scenario. 

Flextesa: 
  initiailizing history file:
  `/tmp/mini-delphi/traffic-generation-history.txt`


Flextesa: Pause  Sandbox is READY \o/ 


(node:48500) UnhandledPromiseRejectionWarning: Error: Bad Request
    at Request.callback (/Users/omar/Desktop/Repositories/tezos-starter-kit/node_modules/ganache-core/node_modules/superagent/src/node/index.js:867:15)
    at IncomingMessage.callback (/Users/omar/Desktop/Repositories/tezos-starter-kit/node_modules/ganache-core/node_modules/superagent/src/node/index.js:1117:18)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:48500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:48500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```

**Comment by kalouo** [comment]
I also tried pruning the docker container.

**Comment by jrhite** [comment]
Looks like a protocol mismatch error.

https://gist.github.com/jrhite/0ef978fc01b6d5bb3eb2fd6cfd2da184

**Comment by dexterslabor** [comment]
Merging fix any moment. Thank you all for reporting and investigating!
